language: perl

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y librdf-perl
install:
  - "cpanm --quiet --notest Module::Install::AuthorTests"
  - "cpanm --quiet --notest Module::Install::DOAPChangeSets"
  - "cpanm --quiet --notest "
  - "cpanm --quiet --notest Attean"
  - "cpanm --quiet --notest File::ShareDir"
  - "cpanm --quiet --notest HTML::HTML5::Parser"
  - "cpanm --quiet --notest HTML::HTML5::Writer"
  - "cpanm --quiet --notest HTTP::Message::PSGI"
  - "cpanm --quiet --notest HTTP::Negotiate"
  - "cpanm --quiet --notest IO::Compress::Gzip"
  - "cpanm --quiet --notest JSON"
  - "cpanm --quiet --notest List::MoreUtils"
  - "cpanm --quiet --notest Moo"
  - "cpanm --quiet --notest MooX::Log::Any"
  - "cpanm --quiet --notest namespace::clean"
  - "cpanm --quiet --notest Plack"
  - "cpanm --quiet --notest Test::Exception"
  - "cpanm --quiet --notest Test::LWP::UserAgent"
  - "cpanm --quiet --notest Test::Modern"
  - "cpanm --quiet --notest Test::Moose"
  - "cpanm --quiet --notest Test::More"
  - "cpanm --quiet --notest Test::Roo"
  - "cpanm --quiet --notest Test::WWW::Mechanize::PSGI"
  - "cpanm --quiet --notest TryCatch"
  - "cpanm --quiet --notest Types::Standard"
script:
  - "perl Makefile.PL && make test"
